# 文件路径: docker-compose.yml

version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: shortlink_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'your_strong_password' # 生产环境请务必使用强密码
      MYSQL_DATABASE: 'shortlink_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis_cache:
    image: redis:7.0-alpine
    container_name: shortlink_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: