# 文件路径: configs/config.yaml

server:
  port: ":8080"
  app_url: "http://localhost:8080/"
  #app_url: "http://192.168.0.6:8080/"

database:
  mysql:
    dsn: "user:password@tcp(127.0.0.1:3307)/shortlink_db?charset=utf8mb4&parseTime=True&loc=Local"

cache:
  redis:
    addr: "localhost:6380"
    password: ""
    db: 0